### ISSUE TITLE
Using library with swift 4

### ISSUE THREAD

**Issue by Beautistar** [joelparkerhenderson/demo_swift_excel_xlsx_reader_writer#3]
I have tried with your repository by adding XlsxWriterReader library and it was working well with your demo project.
So, I was trying to add this in my project with swift4, xcode 9.2
I have added library and setup target dependencies and binary with Libraries.
But, when I add flags, if I add "-all_load", my other framework have issue.
https://prnt.sc/hspvz3
https://prnt.sc/hspwcu
Is this because of swift version or something else?
Thanks.

**Comment by joelparkerhenderson** [comment]
If I understand you, this is what's happening: you are able to run the demo project successfully, and then you are creating your own separate project and want to use the xlsx library. Is this accurate?

If yes, then one way to get help is to ask your question in the library repo: https://github.com/renebigot/XlsxReaderWriter

Notice the library has updates approximately 2 years ago. For time reasons I prefer to have library authors update the libraries to be current, then I update the demo projects. 

If you're stuck and you want to fund a solution, I can provide consulting time. My guess is one hour of time is a likely ballpark. Let me know if you'd like to know more about this.

**Comment by Beautistar** [comment]
Hello, I have solved the problem myself. 
Anyway, thanks for your effort.
